### ISSUE TITLE
Maintain Yearn Docs and Written Content

### ISSUE THREAD

**Issue by saltyfacu** [yearn/budget#69] opened 2022-06-09 12:17 UTC
### Scope

Maintain Yearn Docs and keep adding new content.

docs.yearn.finance is a key resource for developers and integrators. It's critical to maintain it and keep adding tutorials, new docs, and writing new articles.

### Plan

The plan is to keep improving the site and add new content proactively.

This is recurrent but will ask for a 3 months grant. A stream is fine. The date is in September because June was already agreed before this new process.

### Deadline

2022-09-31

### People

Marco Worms: technical writer
saltyfacu: helping out on the organization side

### Money

As a grant for Marco to continue maintaining the work he's been doing

### Amount

15000 DAI

### Wallet address

0xB1d693B77232D88a3C9467eD5619FfE79E80BCCc

### Reporting

- [X] I agree to post weekly updates

**Comment by banteg** [comment] 2022-06-09 13:26
Marco [has a stream](https://llamapay.io/streams?chainId=1&address=0xb1d693b77232d88a3c9467ed5619ffe79e80bccc) already, no additional action required if this is approved.

**Comment by MarcoWorms** [comment] 2022-06-17 14:11
First weekly report, lmk whatever extra info might be needed!

## Docs

I'm super open to receive input of what should be prioritized in our docs, but here is what I've done past week :

* refactor some infrastructure files: https://github.com/yearn/yearn-devdocs/pull/215
* add current budget process: https://github.com/yearn/yearn-devdocs/pull/217
* add veyfi specs (not to be merged until veyfi is in production as requested by facu): https://github.com/yearn/yearn-devdocs/pull/218
* create readme for macarena finance: https://github.com/yearn/macarena-finance/pull/1

**Next week I want to**

* add YIP-66 to the docs https://github.com/yearn/yearn-devdocs/issues/170
* understand from people that consume the docs what could be better (maybe talk to some in-house devs asking which parts they use the most and give them more spotlight)

## Articles

2 articles were done before this week and were waiting for publication so I was communicating with farrah to get them published, I had to deal with some issues I had with the handover of the marketing flows so it wasn't the most productive week for writing new things but we got to reestablish the publishing flow so now things should run smooth:
* yvtokens as collateral got published: https://medium.com/iearn/yearn-vaults-as-collateral-bfacf520a56e
* about sustainable yield (farrah just reviewed so might be done next week): https://hackmd.io/XLCm3SYbQoWAfE8G9Di22A

And I have one draft I'm working on too:
* Yearn and Stablecoins: Analyzing the risks https://hackmd.io/wBddu5IwQZWKz2aLmwSE6Q

**Next week I want to**

* apply all reviews to the sustainable yield article and get it to a publishable state
* finish the stablecoins article to send it for a first review
* start piece on yveCRV and yvBOOST and how yearn interact with curve wars

**Comment by RestlessMike** [comment] 2022-06-17 14:16
Great job, this is the kind of energy, proactiveness and hard work that will make Yearn survive this turbulence.

**Comment by MarcoWorms** [comment] 2022-06-24 16:36
weekly report time!

# Docs

The direction of docs work is still quite open, I'm working on refactoring and upgrading the infrastructure files as I understand what needs to be added next (or how should we reorganize stuff). I talked a bit with Facu about finding some people that use the docs a frequently to give us input on what could be better, but this effort has not began yet

This week's infrastructure upgrade happened at:

- https://github.com/yearn/yearn-devdocs/pull/221
- https://github.com/yearn/yearn-devdocs/pull/223

And I should work on closing old open PRs to work towards zeroing PRs/issues:

- https://github.com/yearn/yearn-devdocs/pull/224

Lastly, I made this guide to fork yearn UI that seems to be in the late stages of review, it's a complementary material to macarena's readme and it's a more extanse guide on the nuances of forking and editing the UI:

- https://github.com/yearn/yearn-devdocs/pull/222

# Articles

I chatted with Farrah about focusing on articles with more deepnes and quality rather than trying to attend a number of articles in a monthly period or anything like this, also I gave more focus to docs/nftreasury this week, so the only tangible progress was absorbing the first batch of reviews in this article:

- Sustainable Yield Article https://hackmd.io/XLCm3SYbQoWAfE8G9Di22A (feedback is welcome)

Did not progress on "Yearn and Stablecoins: Analyzing the risks" this week because I'll focus on finishing the above one before moving on to more articles

**Comment by MarcoWorms** [comment] 2022-07-08 23:12
# Docs

Hello!! So, this week (again)I worked more on NFTreasury (#70) than on tasks from this scope, no that the project is done I'm moving on to documenting our web-lib and will report about this endeavor in the frontend issue:

https://github.com/yearn/budget/issues/70#issuecomment-1179420634

as always, both docs and articles are totally open to suggestions about what could be done! If you think there is something badly documented or you would like to see an article exploring any part of yearn feel free to reach out to me!

# Articles

No progress in new articles this week, the next one I'm working one is an exploration on the inherent risks of holding each stablecoin that we have a vault for at yearn, drafting here: https://hackmd.io/wBddu5IwQZWKz2aLmwSE6Q

**Comment by MarcoWorms** [comment] 2022-07-15 19:26
## Docs

There is some overlapping in "docs" scope since I'm doing web-lib docs [over issue #70](https://github.com/yearn/budget/issues/70#issuecomment-1185836689) and devdocs here, this week I've done docs over there so check that issue for the issues I worked on!

Maybe would be nice to unify the reports in a single issue for future iterations

## Articles

No progress in new articles this week, but in the "marketing" scope I sent a fix for the Portuguese version of bluepill that has the wrong pages order on yfistory website: https://github.com/pentcle/blue-pill/pull/4

Besides the stablecoin-risks draft that I sent on the last report, I'm also thinking of writing an article around subgraph usage

**Comment by MarcoWorms** [comment] 2022-07-22 14:27
## Docs

I polished the governance docs copy this week as well as updated the YIPs table to include them all:

- https://github.com/yearn/yearn-devdocs/pull/227

Also I just did a small improvement to bring all token+contract addresses together in one page at the docs:

- https://github.com/yearn/yearn-devdocs/pull/228

## Articles

I'm not focusing much on articles right now, if anyone has an idea of something you want to see content about just let me know!

**Comment by MarcoWorms** [comment] 2022-07-29 19:49
## Docs

The docs had a bunch of unused code that I think was a reminiscence of old homepages, so I tried to remove code and refactor some things to make it easier to maintain whenever we need to:

- https://github.com/yearn/yearn-devdocs/pull/229

## Articles

I wrote an article about what is and how to use a Subgraph using yearn's one as an example, Dark Ghosty is reviewing it and I should send to Farrah when we're done for one more review + publishing medium:

**Subgraphs explained: Yearning for data**: https://mirror.xyz/blorms.eth/Vz1OioBmYfAHVeUTImCn8OjwlEyy-iSxpGep1wrpU4U

**Comment by MarcoWorms** [comment] 2022-08-05 20:57
## Docs

Open PRS:
- https://github.com/yearn/yearn-devdocs/pull/231
- https://github.com/yearn/yearn-devdocs/pull/229

Issues I'm tackling:
- https://github.com/yearn/yearn-devdocs/issues/233
- https://github.com/yearn/yearn-devdocs/issues/234

## Articles

- Article explaining about subgraph is queued for publication: https://medium.com/@marcoworms/subgraphs-explained-yearning-for-data-4e90d18e33e
- Starting a new one about the most used strategies, what they do, and show their harvest transactions visually

**Comment by MarcoWorms** [comment] 2022-08-12 20:00
## Docs

I'm on the same issues/PRs from last week, when facu comes back from afk we'll merge the PRs

## Articles

- The subgraph article is to be released tomorrow on social medias :D
- I'm doing research for the next one I'm writing about our strategies with most TVL, what they do, and use icevision to provide an overview of their harvest cycle, I got access to the tool and should have a draft by next week, here is an example of how a harvest looks like from the tool's author:
![image](https://user-images.githubusercontent.com/7863230/184433892-c005db8b-3489-41ad-b2b0-5b5f30123735.png)

**Comment by MarcoWorms** [comment] 2022-08-19 19:01
## Docs

I'm working on a PR at vault-descriptions repo that is also inside of scope of #70 to add OP and ARBI vaults and fix some UI parts

- https://github.com/yearn/yearn-vaults-descriptions/pull/67

Waiting on Facu to come back to merge the PR queue on yearn-devdocs

I'm installing the exporter locally and should update the repo's readme with any implicit install instruction, I want to enrich the info we have around both the exporter and the subgraph (which already has a bit more info now https://medium.com/iearn/subgraphs-explained-yearning-for-data-4e90d18e33e)

## Articles

I started to write an article about how our top strategies work but it forked out into different efforts:
- Write a "strategist glossary" that explains the most common used terms like flashmint, fold, flashloan that are used in yearn-meta strategies descriptions (no draft yet)
- Write article explaining current top strategies (draft https://hackmd.io/sZmovYH4SYeVOwerPgyEEQ)

Also another article I want to write is about the github action that Major did to deploy our code on IPFS, I'd like to open up set-by-step how to reproduce this since it adds robustness to the FE decentralization and other protocols could copy/paste

**Comment by MarcoWorms** [comment] 2022-08-26 15:29
## Docs & Articles

Facu came back and merged most things so I sent some other content to devdocs and worked on web-lib docs

- https://github.com/yearn/yearn-devdocs/pull/236
- https://github.com/yearn/yearn-devdocs/pull/237
- https://github.com/yearn/web-lib/pull/77

When validated and shipped I want to make the strategist glossary into a medium article :)  
Web-Lib docs has overlap with #70 scope

**Comment by MarcoWorms** [comment] 2022-09-02 18:02
## Docs & Articles

- https://github.com/yearn/yearn-devdocs/pull/237
The strategy glossary is mostly reviewed but I asked Draper to take a final check at the copy, so I'll wait on him to merge this next week

I'm gonna start 2 articles but nothing done around them yet:

- What is the yDeamon and how to run it locally
- History and present of Yearn Vaults fee structure

**Closed** 2022-10-01 17:13 UTC
Labels: budget request, approved, paid, stream
